# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

project_name: fun
version: 2
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go run scripts/download_deps.go

builds:
  - id: fun
    main: ./main.go
    binary: fun
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.GitCommit={{.ShortCommit}}
    hooks:
      pre: |
        go generate ./... && \
        go run ./container/generate_linuxkit.go -output bin/{{.Os}}-{{.Arch}}/linuxkit/config.yml

msi:
  - id: fun-msi-amd64
    name: "Fun-Server-amd64"
    wxs: installers/windows/app-amd64.wxs
    extra_files:
      - installers/windows/install.ps1
      - installers/windows/uninstall.ps1
      - installers/windows/check-wsl.ps1
      - installers/windows/install-wsl.ps1
      - bin/linux-amd64/runc
      - bin/linux-amd64/containerd
      - bin/linux-amd64/cni/LICENSE
      - bin/linux-amd64/cni/README.md
      - bin/linux-amd64/cni/bandwidth
      - bin/linux-amd64/cni/bridge
      - bin/linux-amd64/cni/dhcp
      - bin/linux-amd64/cni/dummy
      - bin/linux-amd64/cni/firewall
      - bin/linux-amd64/cni/host-device
      - bin/linux-amd64/cni/host-local
      - bin/linux-amd64/cni/ipvlan
      - bin/linux-amd64/cni/loopback
      - bin/linux-amd64/cni/macvlan
      - bin/linux-amd64/cni/portmap
      - bin/linux-amd64/cni/ptp
      - bin/linux-amd64/cni/sbr
      - bin/linux-amd64/cni/static
      - bin/linux-amd64/cni/tap
      - bin/linux-amd64/cni/tuning
      - bin/linux-amd64/cni/vlan
      - bin/linux-amd64/cni/vrf
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"
    version: v4

  - id: fun-msi-arm64
    name: "Fun-Server-arm64"
    wxs: installers/windows/app-arm64.wxs
    extra_files:
      - installers/windows/install.ps1
      - installers/windows/uninstall.ps1
      - installers/windows/check-wsl.ps1
      - installers/windows/install-wsl.ps1
      - bin/linux-arm64/runc
      - bin/linux-arm64/containerd
      - bin/linux-arm64/cni/LICENSE
      - bin/linux-arm64/cni/README.md
      - bin/linux-arm64/cni/bandwidth
      - bin/linux-arm64/cni/bridge
      - bin/linux-arm64/cni/dhcp
      - bin/linux-arm64/cni/dummy
      - bin/linux-arm64/cni/firewall
      - bin/linux-arm64/cni/host-device
      - bin/linux-arm64/cni/host-local
      - bin/linux-arm64/cni/ipvlan
      - bin/linux-arm64/cni/loopback
      - bin/linux-arm64/cni/macvlan
      - bin/linux-arm64/cni/portmap
      - bin/linux-arm64/cni/ptp
      - bin/linux-arm64/cni/sbr
      - bin/linux-arm64/cni/static
      - bin/linux-arm64/cni/tap
      - bin/linux-arm64/cni/tuning
      - bin/linux-arm64/cni/vlan
      - bin/linux-arm64/cni/vrf
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"
    version: v4

dmg:
  - id: fun-dmg
    name: "Fun-Server-{{.Arch}}"
    ids:
      - fun-archives
    extra_files:
      - LICENSE
      - README.md
      - installers/macos/install.sh
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: fun-archives
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
    formats:
      - tar.gz
      - zip
    files:
      - LICENSE
      - README.md
      - installers/{{ .Os }}/*
      - bin/{{ .Os }}-{{ .Arch }}/*
      - bin/linux-{{ .Arch }}/*
    builds:
      - fun
    allow_different_binary_count: true
    format_overrides:
      - goos: windows
        formats:
          - zip
      - goos: darwin
        formats:
          - tar.gz
      - goos: linux
        formats:
          - tar.gz

nfpms:
  - id: fun-linux-packages
    package_name: fun-server
    homepage: https://thefunserver.com
    maintainer: Fun Server Team <team@thefunserver.com>
    description: Fun Server - Self host server software as easily as installing apps on your phone.
    license: Apache-2.0
    vendor: The Fun Server Team
    formats:
      - deb
      - rpm
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
    rpm:
      group: Applications/System
      compression: lzma
    dependencies:
      - bash
    recommends:
      - docker
    builds:
      - fun
    contents:
      - src: installers/linux/fun.service
        dst: /etc/systemd/system/fun.service
      - src: installers/linux/fun.1
        dst: /usr/share/man/man1/fun.1
      - src: bin/linux-{{.Arch}}/runc
        dst: /opt/fun-server/bin/runc
        file_info:
          mode: 0755
      - src: bin/linux-{{.Arch}}/containerd
        dst: /opt/fun-server/bin/containerd
        file_info:
          mode: 0755
      - src: bin/linux-{{.Arch}}/cni/
        dst: /opt/fun-server/bin/cni/
        file_info:
          mode: 0755

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  disable: false
  draft: true
  prerelease: auto
